# Generated by Django 5.1.6 on 2025-03-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='blog_create_title_04f067_idx')],
            },
        ),
    ]
