# Generated by Django 5.1.6 on 2025-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_create_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_post',
            name='email',
        ),
        migrations.AddField(
            model_name='create_post',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
