# Generated by Django 5.1.6 on 2025-03-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_create_post_email_create_post_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create_post',
        ),
    ]
