# Generated by Django 5.1.6 on 2025-03-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_create_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.IntegerField(default=0),
        ),
    ]
